### ISSUE TITLE
postinstall script not included in the release

### ISSUE THREAD

**Issue by mcollina** [mozilla/nunjucks#1075]
As titled:

```
> nunjucks@3.1.1 postinstall /home/travis/build/fastify/point-of-view/node_modules/nunjucks
> node scripts/postinstall-build.js src
module.js:559
    throw err;
    ^
Error: Cannot find module '/home/travis/build/fastify/point-of-view/node_modules/nunjucks/scripts/postinstall-build.js'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:665:3
```

See https://travis-ci.org/fastify/point-of-view/jobs/345481378 and https://github.com/fastify/point-of-view/issues/41.

**Comment by kristate** [comment]
ref #1073

**Comment by fdintino** [comment]
Oh. Right. Because the scripts folder is in `.npmignore`. Okay, I'll push out an emergency release with a fix.

**Comment by fdintino** [comment]
My apologies. The correct script is available in the 3.1.2 release.

**Comment by LeoEatle** [comment]
Still has this issue. My version is 3.1.2.

**Comment by fdintino** [comment]
@LeoEatle I don't doubt that you're experiencing _some_ issue, but it would have to be something other than the current one (you can see by [this travis build](https://travis-ci.org/fastify/point-of-view/builds/345502058) that the original issue from this ticket is resolved with 3.1.2. Please open a new ticket with more details about the issue you're running into.

**Comment by mcollina** [comment]
Thanks for the swift fix!

**Comment by Prasildas** [comment]
HI @fdintino  I had the same error as below:   Tried with npm 3.1.2 and 4.6.2 and 5.6.0. Still not resolved

D:\Location>npm install npm@3.1.2
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for comp
atibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.8: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
npm WARN saveError ENOENT: no such file or directory, open 'D:\555724\Learning\T
ripPlan-CodeSkeleton\package.json'
npm WARN npm@3.1.2 had bundled packages that do not match the required version(s
). They have been replaced with non-bundled versions.
npm WARN enoent ENOENT: no such file or directory, open 'D:\555724\Learning\Trip
Plan-CodeSkeleton\package.json'
npm WARN TripPlan-CodeSkeleton No description
npm WARN TripPlan-CodeSkeleton No repository field.
npm WARN TripPlan-CodeSkeleton No README data
npm WARN TripPlan-CodeSkeleton No license field.

+ npm@3.1.2
added 14 packages from 4 contributors and updated 1 package in 19.029s

D:\555724\Learning\TripPlan-CodeSkeleton>node server
module.js:559
    throw err;
    ^

Error: Cannot find module 'D:\...\server'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:660:3

**Comment by fdintino** [comment]
@Prasildas I don't see anything in your stack trace that suggests that nunjucks is causing your issue.
